baseURL = "http://ryouze.net/"
title = "ryouze"
theme = "gokarna"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true
pygmentsStyle = "monokai"  # Code highlighting style
contentDir = "content"
enableGitInfo = true


[params]
  # Landing page
  ## Avatar
  avatarURL = "https://avatars.githubusercontent.com/u/98982999"
  AvatarAltText = "avatar"
  avatarSize = "size-l"  # size-xs, size-s, size-m, size-l & size-xl (default: size-m)
  ## Title
  description = "Jan Foremski"
  ## Icons with links below the avatar the title / description: https://github.com/526avijitgupta/gokarna/tree/main/static/svg/icons
  socialIcons = [
    {name = "github", url = "https://github.com/ryouze"},
    {name = "email", url = "mailto:mirai@ryouze.net"}
  ]
  ## Posts: "popular" (order posts by weight), "recent" (order posts by date), or "" (do not display, default option)
  showPostsOnHomePage = "recent"
  ## Number of posts to show on the homepage
  NumberPostsOnHomePage = 6

  # Appearance
  ## Display a "back to top" button on posts
  ShowBackToTopButton = true
  ## Display reading time on posts
  DisplayReadingTime = true
  ## Date format
  dateFormat = "02.01.2006 @ 15:04"
  ## Previous and Next buttons (will not work with the ".Weight" parameter)
  TogglePreviousAndNextButtons = true

  # Misc
  ## SEO
  metaKeywords = ["ryouze", "GitHub", "Tutorial", "Programming", "Blog", "C++", "Python", "macOS", "Linux"]
  ## Author information for structured data
  author = "ryouze"


[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Projects"
    pre = "<span data-feather='code'></span>"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    name = "GitHub"
    pre = "<span data-feather='github'></span>"
    url = "https://github.com/ryouze/"
    weight = 3

    [menu.main.params]
      newPage = true

  [[menu.main]]
    name = "Posts"
    pre = "<span data-feather='book'></span>"
    url = "/posts/"
    weight = 4

  [[menu.main]]
    name = "Contact"
    pre = "<span data-feather='mail'></span>"
    url = "/contact/"
    weight = 5

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false
