theme = "gokarna"

title = "ryouze"
baseURL = "https://ryouze.net/"

locale = "en"
defaultContentLanguage = "en"

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true


[params]
  description = "Jan Foremski"
  avatarURL = "https://avatars.githubusercontent.com/u/98982999"

  AvatarAltText = "avatar"
  avatarSize = "size-l"  # size-xs, size-s, size-m, size-l & size-xl (default: size-m)

  socialIcons = [
    # https://github.com/526avijitgupta/gokarna/tree/main/static/svg/icons
    {name = "github", url = "https://github.com/ryouze"},
    {name = "linkedin", url = "https://www.linkedin.com/in/jan-foremski-ab60122b8/"},
    {name = "email", url = "mailto:mirai@ryouze.net"}
  ]

  NumberPostsOnHomePage = 6

  DisplayReadingTime = true
  ShowBackToTopButton = true
  dateFormat = "2006-01-02 15:04"
  TogglePreviousAndNextButtons = true  # Will not work with the ".Weight" parameter
  showPostsOnHomePage = "recent"  # "popular" (order posts by weight), "recent" (order posts by date), or "" (do not display, default)

  # SEO
  author = "Jan Foremski"
  metaKeywords = ["ryouze", "GitHub", "Tutorial", "Programming", "Blog", "C++", "Python", "macOS", "Linux"]


[menus]
  [[menus.main]]
    weight = 1
    name = "Home"
    pageRef = "/"
    pre = "<span data-feather='home'></span>"

  [[menus.main]]
    weight = 2
    name = "Projects"
    pageRef = "/projects"
    pre = "<span data-feather='code'></span>"

  [[menus.main]]
    weight = 3
    name = "GitHub"
    url = "https://github.com/ryouze/"
    pre = "<span data-feather='github'></span>"

    [menus.main.params]
      newPage = true

  [[menus.main]]
    weight = 4
    name = "Posts"
    pageRef = "/posts"
    pre = "<span data-feather='book'></span>"

  [[menus.main]]
    weight = 5
    name = "Contact"
    pageRef = "/contact"
    pre = "<span data-feather='mail'></span>"

[markup]
  [markup.highlight]
    style = "monokai"
